### ISSUE TITLE
Removing sensor from IoTaWatt device causes errors

### ISSUE THREAD

**Issue by gtdiehl** [gtdiehl/iotawatt_ha#1]
When removing a sensor from the IoTaWatt webpage, Home Assistant tries to update the state of the removed sensor and results in the errors in the log to appear for every poll

```
Traceback (most recent call last):
  File "/Users/greg/Documents/GitHub/core/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/Users/greg/Documents/GitHub/core/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/Users/greg/Documents/GitHub/core/homeassistant/helpers/update_coordinator.py", line 245, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/Users/greg/Documents/GitHub/core/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/Users/greg/Documents/GitHub/core/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/Users/greg/Documents/GitHub/core/homeassistant/components/iotawatt/sensor.py", line 89, in state
    return self.coordinator.data["sensors"][self._ent].getValue()
KeyError: 'output_mhghjk'
```

**Comment by mmiller7** [comment]
Same issue - can't figure out how to remove an old sensor without deleting the entire addon and reinstalling.

**Comment by jherby2k** [comment]
Renaming an output causes havok as well

**Comment by gtdiehl** [comment]
Any ideas on how to if this? 🤷 

Ideally, I would want to resolve this one before submitting it to the HA repo for inclusion.

**Comment by gtdiehl** [comment]
I fixed the issue on the API side and released a new version to PyPi ```0.0.7```. The issue is now in the IoTaWatt sensor code

```2021-08-07 22:11:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/workspaces/core/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/workspaces/core/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/workspaces/core/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/workspaces/core/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/workspaces/core/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/workspaces/core/homeassistant/components/iotawatt/sensor.py", line 103, in state
    return self.coordinator.data["sensors"][self._ent].getValue()
KeyError: 'output_vvv'

**Comment by balloob** [comment]
Step 1 is to add a new `available` property so it won't fetch the state anymore:

```python
@property
def available(self) -> bool:
    """Return if entity is available."""
    return super().available and self._ent in self.coordinator.data["sensors"]
```

**Comment by balloob** [comment]
That way it will be marked as unavailable and won't cause a key error.

A more proper fix is to remove the sensor completely. You can do that by overriding [`_handle_coordinator_update`](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/update_coordinator.py#L322-L325) in sensor entity. If the key doesn't exist anymore in the output, delete the entity:

```python
from homeassistant.helpers import entity_registry

    @callback
    def _handle_coordinator_update(self) -> None:
        """Handle updated data from the coordinator."""
        if self._ent not in self.coordinator.data["sensors"]:
            entity_registry.async_get(self.hass).async_remove(self.entity_id)
            return

        super()._handle_coordinator_update()
```

**Comment by bmorgan99** [comment]
Just got my IoTaWatt installed and was wondering if this was the last remaining obstacle for core inclusion.  Should I go ahead with HACS?
